apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: cocaco10/payment-service
        env:
          - name: MONGO_URI
            value: 'mongodb://payment-mongo-service:27017/payments'
          - name: JWT_KEY
            valueFrom:  
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_URL
            value: 'http://nats-service:4222'
          - name: NATS_CLIENT_ID
            valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
          - name: STRIPE_KEY
            valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY 

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 3000
      targetPort: 3000