apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
      - name: ticket
        image: cocaco10/ticket-service
        env:
          - name: MONGO_URI
            value: 'mongodb://ticket-mongo-service:27017/tickets'
          - name: JWT_KEY
            valueFrom:  
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: NATS_URL
            value: 'http://nats-service:4222'
          - name: NATS_CLIENT_ID
            valueFrom:
                  fieldRef:
                    fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  selector:
    app: ticket
  ports:
    - name: ticket
      protocol: TCP
      port: 3000
      targetPort: 3000